name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Run miri
        run: ci/miri.sh    
  tests:
    strategy:
      matrix:
        rust:
          - nightly
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rustflags:
          - '-C target-cpu=native'
          - '-C target-cpu=native -C target-feature=-avx2'
        features:
          - ''
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Run tests
        run: cargo test ${{ matrix.features }} --release
